Update opkg-call

diff --git a/applications/luci-app-opkg/root/usr/libexec/opkg-call b/applications/luci-app-opkg/root/usr/libexec/opkg-call
--- a/applications/luci-app-opkg/root/usr/libexec/opkg-call
+++ b/applications/luci-app-opkg/root/usr/libexec/opkg-call
@@ -16,10 +16,10 @@ case "$action" in
 	install|update|remove)
 		(
 			opkg="opkg"
-
+			pkg=$5
 			while [ -n "$1" ]; do
 				case "$1" in
-					--autoremove|--force-overwrite|--force-removal-of-dependent-packages)
+					--autoremove|--force-overwrite|--force-removal-of-dependent-packages|--force-checksum|--force-depends)
 						opkg="$opkg $1"
 						shift
 					;;
@@ -34,6 +34,12 @@ case "$action" in
 
 			if flock -x 200; then
 				$opkg $action "$@" </dev/null >/tmp/opkg.out 2>/tmp/opkg.err
+				sed -i "/resolve_conffiles/d" /tmp/opkg.err || true
+				sed -i "/uci: Entry not found/d" /tmp/opkg.err || true
+				sed -i "/Existing conffile/d" /tmp/opkg.err || true
+				sed -i "/Couldn't unlink/d" /tmp/opkg.err || true
+				sed -i "/pkg_hash_check_unresolved/d" /tmp/opkg.err || true
+				[ "`cat /tmp/opkg.err`" == "Collected errors:" ] && rm -f /tmp/opkg.err || true
 				code=$?
 				stdout=$(cat /tmp/opkg.out)
 				stderr=$(cat /tmp/opkg.err)
@@ -47,6 +53,18 @@ case "$action" in
 			[ -n "$stdout" ] && json_add_string stdout "$stdout"
 			[ -n "$stderr" ] && json_add_string stderr "$stderr"
 			json_dump
+
+		case "$action" in
+			install)
+				[[ "$(echo $(opkg list-installed) | grep $pkg)" ]] && {
+				echo $pkg >>/etc/backup/aa.txt
+				}
+			;;
+			remove)
+				sed -i "/$pkg/d" /etc/backup/aa.txt
+				
+			;;
+		esac
 		) 200>/tmp/opkg.lock
 
 		rm -f /tmp/opkg.lock /tmp/opkg.err /tmp/opkg.out
