Update opkg-call

diff --git a/applications/luci-app-opkg/root/usr/libexec/opkg-call b/applications/luci-app-opkg/root/usr/libexec/opkg-call
--- a/applications/luci-app-opkg/root/usr/libexec/opkg-call
+++ b/applications/luci-app-opkg/root/usr/libexec/opkg-call
@@ -19,7 +19,7 @@ case "$action" in
 
 			while [ -n "$1" ]; do
 				case "$1" in
-					--autoremove|--force-overwrite|--force-removal-of-dependent-packages)
+					--autoremove|--force-overwrite|--force-removal-of-dependent-packages|--force-checksum|--force-depends)
 						opkg="$opkg $1"
 						shift
 					;;
@@ -34,6 +34,15 @@ case "$action" in
 
 			if flock -x 200; then
 				$opkg $action "$@" </dev/null >/tmp/opkg.out 2>/tmp/opkg.err
+				if [[ $@ == "luci-app-*" ]]; then
+					$opkg $action luci-i18n-"$(echo $@ | cut -d - -f 3-4)"-zh-cn >/dev/null
+				fi
+				sed -i "/resolve_conffiles/d" /tmp/opkg.err || true
+				sed -i "/uci: Entry not found/d" /tmp/opkg.err || true
+				sed -i "/Existing conffile/d" /tmp/opkg.err || true
+				sed -i "/Couldn't unlink/d" /tmp/opkg.err || true
+				sed -i "/pkg_hash_/d" /tmp/opkg.err || true
+				[ "`cat /tmp/opkg.err`" == "Collected errors:" ] && rm -f /tmp/opkg.err || true
 				code=$?
 				stdout=$(cat /tmp/opkg.out)
 				stderr=$(cat /tmp/opkg.err)
@@ -47,6 +56,18 @@ case "$action" in
 			[ -n "$stdout" ] && json_add_string stdout "$stdout"
 			[ -n "$stderr" ] && json_add_string stderr "$stderr"
 			json_dump
+
+		case "$action" in
+			install)
+				[[ "$(opkg list-installed | cut -f 1 -d ' ' | grep $@)" ]] && {
+				echo $@ >>/etc/backup/user_installed.opkg
+				}
+			;;
+			remove)
+				sed -i "/$@/d" /etc/backup/user_installed.opkg
+				sed -i 'luci-i18n-"$(echo $@ | cut -d - -f 3-4)"-zh-cn/d' /etc/backup/user_installed.opkg
+			;;
+		esac
 		) 200>/tmp/opkg.lock
 
 		rm -f /tmp/opkg.lock /tmp/opkg.err /tmp/opkg.out
